# Generated by Django 5.1 on 2024-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_category_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_task_name', models.CharField(max_length=100)),
                ('easy_task', models.CharField(max_length=200)),
                ('easy_time', models.DateTimeField()),
            ],
        ),
    ]
