# Generated by Django 5.1 on 2024-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_hard'),
    ]

    operations = [
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=100)),
            ],
        ),
    ]
