# Generated by Django 5.1 on 2024-09-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S',
        ),
    ]
