# Generated by Django 5.1 on 2024-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_hard_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='easy',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
