# Generated by Django 5.1 on 2024-09-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_is_completed_task_is_completed_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed_task',
            new_name='is_completed',
        ),
    ]
