# Generated by Django 5.1 on 2024-09-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_rename_is_completed_task_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easy',
            old_name='easy_task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='easy',
            old_name='easy_task_name',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='easy',
            old_name='easy_time',
            new_name='time',
        ),
        migrations.CreateModel(
            name='task_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.category')),
            ],
        ),
    ]
